name: Java Maven Build Check (No Tests)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and package with Maven, skipping tests
      run: mvn -B package -DskipTests --file pom.xml